### ISSUE TITLE
Add LICENCE

### ISSUE THREAD

**Issue by mshodge** [datasciencecampus/readpyne#1]
Hey @finnkauski can you add a LICENCE file to this. MIT or ONS specific, whichever you feel appropriate. Trying to get LICENCE docs on all our public repos.

**Comment by dmaroulidis** [comment]
Hi! I'd be more than happy to add a LICENCE file to the repo.

**Comment by mshodge** [comment]
Thanks @dmaroulidis, LICENCE files should ideally come from within the Campus, so I will create one today. Same goes for @datasciencecampus/optimus PR.
